workflows:
  ios-mapacc:
    name: MapaCC iOS
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: 16.3
      cocoapods: default
    scripts:
      - name: Install pods
        script: |
          cd src
          pod install
      - name: Build iOS app
        script: |
          cd src
          xcodebuild build \
            -workspace MapaCC.xcworkspace \
            -scheme MapaCC \
            -configuration Debug \
            -sdk iphonesimulator
