workflows:
  ios-mapacc:
    name: MapaCC iOS
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      xcode: 16.3
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: br.com.mapacc.app

    scripts:
      - name: Install pods
        script: |
          cd src
          pod install

      - name: Set up code signing
        script: |
          cd src
          xcode-project use-profiles



      - name: Build IPA verbose
        script: |
          cd src
          set -o pipefail
          xcodebuild archive \
            -workspace MapaCC.xcworkspace \
            -scheme MapaCC \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -sdk iphoneos \
            -archivePath build/ios/xcarchive/MapaCC.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist exportOptions.plist
            DEVELOPMENT_TEAM=6TQTTMXW8H \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="MapaCC App Store" \
            | tee xcodebuild.log

    artifacts:
      - src/xcodebuild.log
      - src/build/ios/xcarchive/*.xcarchive
      - src/build/ios/ipa/*.ipa
